WeddingAzure/Models/Accommodation.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WeddingAzure.Models
{
    public class Accommodation
    {
        public string Name { get; set; }
        public string Address  { get; set; }
        public string Phone  { get; set; }
        public string Description { get; set; }
        public string Link { get; set; }
        public bool IsMainChoice { get; set; }
        
        public Accommodation(
            string name,
            string address,
            string phone,
            string description,
            string link,
            bool isMainChoice)
        {
            Name = name;
            Address = address;
            Phone = phone;
            Description = description;
            Link = link;
            IsMainChoice = isMainChoice;
        }
    }
}

WeddingAzure/Models/RsvpFormData.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.UI.WebControls;

namespace WeddingAzure.Models
{
    public class RsvpFormData
    {
        [Required(ErrorMessage = "* Name is required")]
        [Display(Name = "Name(s)")]
        [StringLength(100, MinimumLength = 2, ErrorMessage = "* Name must be between 2 and 100 characters.")]
        public string NameTextBoxData { get; set; }

        [Display(GroupName = "AttendingWedding", Name="Is ready to see you get married")]
        public bool AttendingWeddingCheckBox { get; set; }
        
        [Display(GroupName = "WillToastFromAfar", Name = "Will toast you from afar")]
        public bool WillToastFromAfar { get; set; }

        [Display(GroupName = "AttendingSunday", Name = "Will attend Pop in the Park")]
        public bool AttendingSundayCheckBox { get; set; }

        [Display(Name = "Dietary Requirements")]
        public string DietaryRequirementsTextBoxData { get; set; }
        
        [Display(Name = "I'll only dance if you play... ")]
        public string SongRequestTextBoxData { get; set; }
    }
}

WeddingAzure/Models/WeddingPartyMember.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WeddingAzure.Models
{
    public class WeddingPartyMember
    {
        public string ImageSrc { get; set; }
        public string Name { get; set; }
        public string Role { get; set; }
        public string Description { get; set; }
        public WeddingParty WeddingParty { get; set; }

        public WeddingPartyMember(
            string imageSrc,
            string name,
            string role,
            string description,
            WeddingParty weddingParty)
        {
            ImageSrc = imageSrc;
            Name = name;
            Role = role;
            Description = description;
            WeddingParty = weddingParty;
        }
    }

    public enum WeddingParty
    {
        Lizi,
        Andy,
    }
}

WeddingAzure/Controllers/GalleryController.cs
using Sprague.Andy.WeddingAzure.DataAccess.Rsvp;
using Sprague.Andy.WeddingAzure.Models.Rsvp;
using System.Threading.Tasks;
using System.Web.Mvc;
using Serilog;
using Sprague.Andy.WeddingAzure.DataAccess;
using Sprague.Andy.WeddingAzure.DataAccess.Mail;

namespace WeddingAzure.Controllers
{
    public class GalleryController : Controller
    {
        public static ILogger _log = Log.ForContext<GalleryController>();

        public ActionResult Index()
        {
            ViewBag.Message = "Gallery.";

            return View();
        }

        protected override void OnException(ExceptionContext filterContext)
        {
            filterContext.ExceptionHandled = true;

            //Log the error!!
            _log.Error(filterContext.Exception.Message);

            filterContext.Result = new ViewResult
            {
                ViewName = "~/Views/Shared/Error.cshtml"
            };
        }
    }
}

WeddingAzure/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WeddingAzure.Factories;
using WeddingAzure.Models;
using WeddingAzure.Services;

namespace WeddingAzure.Controllers
{
    public class HomeController : Controller
    {
        private static readonly IImageService _imageService = new AzureBlobStoreImageService(
            "landowedding",
            "8j7qKtXTrFUFK3xjrZ3GBRxqvIay+/8divHV6Mmy5rwis16+f5ACG9FDFbqcxVnB7l1vrM5EzAvB8IgautEI8g=="
        );

        public ActionResult Index()
        {
            ViewBag.DaysToGo = (DateTime.Parse("2018-05-26") - DateTime.Today).TotalDays;
            ViewBag.JumbotronImage = _imageService.GetImageUri("img", "italy-like-a-bird.jpg");
            ViewBag.IconImage = _imageService.GetImageUri("img", "wedding-icon.png");
            var weddingParty = WeddingPartyFactory.GetWeddingPartyMembers(_imageService);
            return View(weddingParty);
        }

        public ActionResult Details()
        {
            var accommodations = AccommodationFactory.GetAccommodations();

            ViewBag.Message = "Your application details page.";

            return View(accommodations);
        }

        public ActionResult Gifts()
        {
            return View();
        }      
    }
}

WeddingAzure/Controllers/RsvpController.cs
using Sprague.Andy.WeddingAzure.DataAccess.Rsvp;
using Sprague.Andy.WeddingAzure.Models.Rsvp;
using System.Threading.Tasks;
using System.Web.Mvc;
using Serilog;
using Sprague.Andy.WeddingAzure.DataAccess;
using Sprague.Andy.WeddingAzure.DataAccess.Mail;

namespace WeddingAzure.Controllers
{
    public class RsvpController : Controller
    {
        public static ILogger _log = Log.ForContext<RsvpController>();

        public ActionResult Index()
        {
            ViewBag.Message = "RSVP Page.";

            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Index(Models.RsvpFormData formData)
        {
            if (formData.SongRequestTextBoxData != null && formData.SongRequestTextBoxData.ToLower().Contains("spice girl"))
            {
                ModelState.AddModelError("SongRequestTextBoxData", "Spice Girls? Seriously?");    
            }

            if (ModelState.IsValid)
            {
                var config = new ServiceConfiguration();
                var repo = new RsvpRepository(config);

                var rsvpEntity = new RsvpEntity(formData.NameTextBoxData)
                {
                    AttendingWedding = formData.AttendingWeddingCheckBox,
                    WillToastFromAfar = formData.WillToastFromAfar,
                    AttendingPopInThePark = formData.AttendingSundayCheckBox,
                    DietaryRequirements = formData.DietaryRequirementsTextBoxData,
                    SongRequest = formData.SongRequestTextBoxData
                };

                await repo.AddOrReplaceRsvpAsync(rsvpEntity);

                var email = new EmailManager(config);
                email.SendRsvpRecieved(rsvpEntity);

                return View("Success", formData);
            }
            return View(formData);
        }

        public ActionResult Success(Models.RsvpFormData formData)
        {
           return View(formData);
        }

        protected override void OnException(ExceptionContext filterContext)
        {
            filterContext.ExceptionHandled = true;

            //Log the error!!
            _log.Error(filterContext.Exception.Message);

            filterContext.Result = new ViewResult
            {
                ViewName = "~/Views/Shared/Error.cshtml"
            };
        }
    }
}

WeddingAzure/Views/Gallery/Index.cshtml
@{
    ViewBag.Title = "#Lando2018 - Gallery";
}

<!--https://www.publicalbum.org/blog/embedding-google-photos-albums-->
<!--<script async src="https://www.publicalbum.org/js/pa-ins.min.js"></script>-->
<script src="../../juicebox/jbcore/juicebox.js"></script>

<div class="col-xs-12"><h2>Photos</h2></div>
<div class="row">
    <p><i>Credit and the warmest of thanks go to our amazing local photographers Phil and Giles</i></p>
    <div class="col-xs-12 col-md-6">
        <h3>Wedding Morning</h3>
        <div class="gallery" style="height: 300px;">
            <!--START JUICEBOX EMBED-->
            <script type="text/javascript">
                new juicebox({
                    containerId: 'jb-container-morning',
                    baseURL: '../../juicebox/morning/',
                    galleryWidth: '100%',
                    galleryHeight: '100%',
                    backgroundColor: 'rgba(34,34,34,1)'
                });
            </script>
            <div id="jb-container-morning"></div>
            <!--END JUICEBOX EMBED-->
        </div>
        <p class="gallery-download"><a href="https://flic.kr/s/aHskBcBWTH">View on Flikr and Download!</a></p>
    </div>
    <div class="col-xs-12 col-md-6">
        <h3>Wedding Ceremony</h3>
        <div class="gallery" style="height: 300px;">
            <!--START JUICEBOX EMBED-->
            <script type="text/javascript">
                new juicebox({
                    containerId: 'jb-container-ceremony',
                    baseURL: '../../juicebox/ceremony/',
                    galleryWidth: '100%',
                    galleryHeight: '100%',
                    backgroundColor: 'rgba(34,34,34,1)'
                });
            </script>
            <div id="jb-container-ceremony"></div>
            <!--END JUICEBOX EMBED-->
        </div>
        <p class="gallery-download"><a href="https://flic.kr/s/aHsmiX8iZu">View on Flikr and Download!</a></p>
    </div>
    <div class="col-xs-12 col-md-6">
        <h3>Wedding Reception</h3>
        <div class="gallery" style="height: 300px;">
            <!--START JUICEBOX EMBED-->
            <script type="text/javascript">
                new juicebox({
                    containerId: 'jb-container-reception',
                    baseURL: '../../juicebox/reception/',
                    galleryWidth: '100%',
                    galleryHeight: '100%',
                    backgroundColor: 'rgba(34,34,34,1)'
                });
            </script>
            <div id="jb-container-reception"></div>
            <!--END JUICEBOX EMBED-->
        </div>
        <p class="gallery-download"><a href="https://flic.kr/s/aHsmiX9Upj">View on Flikr and Download!</a></p>
    </div>
    <div class="col-xs-12 col-md-6">
        <h3>Pop in the Park</h3>
        <div class="gallery" style="height: 300px;">
            <!--START JUICEBOX EMBED-->
            <script type="text/javascript">
                new juicebox({
                    containerId: 'jb-container-pop',
                    baseURL: '../../juicebox/pop/',
                    galleryWidth: '100%',
                    galleryHeight: '100%',
                    backgroundColor: 'rgba(34,34,34,1)'
                });
            </script>
            <div id="jb-container-pop"></div>
            <!--END JUICEBOX EMBED-->
        </div>
        <p class="gallery-download"><a href="https://flic.kr/s/aHskBcFabn">View on Flikr and Download!</a></p>
    </div>
</div>
<div class="row">
    <div class="col-xs-2"></div>
    <div class="col-xs-8 " id="groupphotogallery">
        <h3>Group Photos</h3>

        <div class="gallery" style="height: 500px;">
            <!--START JUICEBOX EMBED-->
            <script type="text/javascript">
                    new juicebox({
                        containerId: 'jb-container-group',
                        baseURL: '../../juicebox/group/',
                        galleryWidth: '100%',
                        galleryHeight: '100%',
                        backgroundColor: 'rgba(34,34,34,1)'
                    });
            </script>
            <div id="jb-container-group"></div>
            <!--END JUICEBOX EMBED-->
            <p class="gallery-download"><a href="https://flic.kr/s/aHsmeWX7s1">View on Flikr and Download!</a></p>
        </div>
    </div>
    <div class="col-xs-2"></div>
</div>
<div class="row">
<span class="glyphicon glyphicon-heart"></span>
</div>
<hr />

<p>Print quality versions of all photos are available on request, just ask or email <a href="mailto:landyshared@gmail.com">landyshared@gmail.com</a></p>

<hr />
<div class="row">
<div class="col-xs-12">
        <h3>Honeymoon</h3>
            
        <p class="gallery-download"><a href="https://photos.app.goo.gl/Jcd9vGeetx1cGBg56">View our best honeymoon pics in Google Photos!</a></p>
    </div>
</div>
<hr />

<div class="row">
<span class="glyphicon glyphicon-heart"></span>
</div>
<hr />
<div class="row" id="videos">
<div class="col-xs-12"><h2>Films</h2></div>
<div class="col-xs-12">
    <p>Please click the following to view the highlights of the day and a feature film (password: l&a)</p>
    <p>Credit goes to <a href="www.newlywedfilms.com">Newlywed Films</a></p>
    <p class="gallery-download" style="margin-top:20px"><a href="https://vimeo.com/278235468">Highlights</a></p>
    <p class="gallery-download" style="margin-top:20px"><a href="https://vimeo.com/278236134">Feature</a></p>
</div>
</div>

<div class="row">
    <span class="glyphicon glyphicon-heart"></span>
</div>

WeddingAzure/Views/Home/Details.cshtml
@using System.Linq
@using System.Web.DynamicData
@using WeddingAzure.Models
@model System.Collections.Generic.IEnumerable<WeddingAzure.Models.Accommodation>

@{
    ViewBag.Title = "#Lando2018 - Details";
}

<div class="row" id="accomodation">
    <div class="col-xs-12"><h2>Accomodation</h2></div>
    @foreach (var item in Model.Where(m => m.IsMainChoice))
    {
        <div class="row">
            <div class="col-xs-12"><h3>@Html.DisplayFor(modelItem => item.Name) </h3></div>
            <div class="col-xs-12"><p>@Html.DisplayFor(modelItem => item.Address)</p></div>
            <div class="col-xs-12"><p class="p-justify p-center-md-4">@Html.DisplayFor(modelItem => item.Description) </p></div>
            <div class="col-xs-12"><a href="@Html.DisplayFor(modelItem => item.Link)"> @Html.DisplayFor(modelItem => item.Name) Website </a></div>
        </div>
        <hr />
    }
    <div class="col-xs-12"><h2>Other Options</h2></div>
    @foreach (var item in Model.Where(m => !m.IsMainChoice))
    {
        <div class="col-xs-12 col-md-4">
            <div><h3>@Html.DisplayFor(modelItem => item.Name) </h3></div>
            <div><p>@Html.DisplayFor(modelItem => item.Address)</p></div>
            <div><p class="p-justify p-description">@Html.DisplayFor(modelItem => item.Description) </p></div>
            <div><a href="@Html.DisplayFor(modelItem => item.Link)"> @Html.DisplayFor(modelItem => item.Name) Website </a></div>
        </div>
    }
</div>
<hr />
<div class="row" id="sitters">
    <div class="col-xs-12"><h2>Baby Sitters</h2></div>
    <div class="col-xs-12 p-center"><p class="p-center">Those requiring baby sitters in the Surrey area:</p></div>
    <div class="col-xs-12">
        <a href="http://www.sitters.co.uk/baysitters-in-surrey.aspx">www.babysitters.co.uk</a>
    </div>
</div>
<hr />
<div class="row" id="sundayaccomodation">
    <div class="col-xs-12"><h2>Sunday accomodation</h2></div>
    <div class="col-xs-12 p-center"><p class="p-center">If you require accomodation after Pop in the Park on Sunday, please follow the link to 
        find some recommendations of hotels in the Godalming area:</p></div>
    <div class="col-xs-12">
        <a href="https://www.tripadvisor.com/SmartDeals-g635924-Godalming_Surrey_England-Hotel-Deals.html">TripAdvisor Godalming</a>
    </div>
</div>
<hr />


<div class="row" id="venuemap">
    <div class="col-xs-2"></div>
    <div class="col-xs-8">
        <div style="position: relative; width: 100%; height: 0; padding-bottom: 75%;">
            <iframe style="position: absolute; left: 0; top: 0; width: 100%; height: 100%"
                    src="https://www.google.com/maps/d/u/0/embed?mid=1pdpEokbjsiwljVvZu0rTgDSWOamGpZA3"></iframe>
        </div>
    </div>
    <div class="col-xs-2"></div>
</div>

WeddingAzure/Views/Home/Gifts.cshtml
@{
    ViewBag.Title = "#Lando2018 - Gifts";
}

<div class="row" id="gift">
    <div class="col-xs-12"><h2>Gifts</h2></div>

    <div class="row">
        <div class="col-xs-2"></div>
        <div class="col-xs-8 " id="giftpoem">
            <p>As our wedding day draws near</p>
            <p>We hope our sentiment is clear</p>
            <p>We need you there as we are wed </p>
            <p>To witness our love as vows are said </p>
            <p>-</p>
            <p>But as for gifts, please please don’t try</p>
            <p>To find the ideal thing to buy</p>
            <p>We have no list of pots and pans</p>
            <p>Just hopes and dreams and honeymoon plans</p>
            <p>-</p>
            <p>So if a gift is on your mind</p>
            <p>A contribution would be kind</p>
            <p>It will help us more than words can say</p>
            <p>To celebrate our special day</p>
            <p>-</p>
            <p>Thank you</p>
        </div>
        <div class="col-xs-2"></div>
    </div>
</div>
<hr />
<div class="row">
    <span class="glyphicon glyphicon-heart"></span>
</div>
<hr />

WeddingAzure/Views/Home/Index.cshtml
@using System.Linq
@using WeddingAzure.Models
@model System.Collections.Generic.IEnumerable<WeddingAzure.Models.WeddingPartyMember>

@{
    ViewBag.Title = "#Lando2018 - Home";
}

<div class="jumbotron" id="jumbo">
    <p id="quote">Every love story is beautiful, but ours is my favourite</p>
</div>

<div class="row">
    <div class="col-xs-12" id="banner">
        <h2>Lizi & Andy</h2>
        <p class="p-banner">May 26, 2018 <span class="glyphicon glyphicon-heart"></span> Thanks for coming!</p>
    </div>
</div>
<hr/>
<div class="row">
    <div class="col-xs-12"><h2>The Wedding </h2></div>
    <div class="col-xs-12"><p>Denbies Wine Estate, Dorking, RH5 6AA, UK</p></div>
    <div class="col-xs-12"><p>2:00pm for 2:30pm </p></div>
    <div class="col-xs-12"><p>Attire: Smart</p></div>
    <div class="col-xs-12" id="weddingNote"><p>We love your kids but thought you might like a night off. Adults only please!</p></div>
</div>
<hr />
<div class="row">
    <div class="col-xs-12"><h2>Pop in the Park </h2></div>
    <div class="col-xs-12"><p>Sunday, May 27, 2018</p></div>
    <div class="col-xs-12"><p>Phillips Memorial Park, Godalming, GU7 1EP, UK</p></div>
    <div class="col-xs-12"><p>From 2:00pm</p></div>
    <div class="col-xs-12" id="popNote"><p>Time for a prosecco or two? Please join our post-wedding party. Bring the kids, there’s cake!</p></div>
</div>
<hr />
<div class="row">
    <span class="glyphicon glyphicon-heart"></span>
</div>
<hr />
<div class="row" id="ourStory">
    <div class="col-xs-12" ><h2>Our Story</h2></div>
    <div class="col-xs-2"></div>
    <div class="col-xs-8">
        <p class="p-justify">Lizi and Andy met at an awkward dinner party.
            Awkward because Lizi burnt the spaghetti! 
            Then on their first date they tried to convince the other they were ‘cultural’ when they arranged
            to meet at the V&A museum, only to find it was shut. It only took Andy three weeks to ask Lizi whether
            she would ‘officially’ be his girlfriend, but it took another three years for him to finally build
            up the courage to ask the big question…
        </p>
        <p>'“Will you move to America with me?” She said yes, and the rest is history!</p>
    </div>
    <div class="col-xs-2"></div>
</div>
<hr />
<div class="row">
    <span class="glyphicon glyphicon-heart"></span>
</div>
<hr/>
<div class="row">
    <div class="col-xs-12"><h2>Wedding Party</h2></div>
    <div class="col-xs-12 col-md-6" id="andyWeddingParty">
        @foreach (var item in Model.Where(modelItem => modelItem.WeddingParty == WeddingParty.Andy))
        {
            <div class="row">
                <div class="col-xs-12">
                    <div class="col-xs-4">
                        <img class="img-circle" 
                             src="@Html.DisplayFor(modelItem => item.ImageSrc)" 
                             alt="@Html.DisplayFor(modelItem => item.Name)"/>
                    </div>
                    <div class="col-xs-8">
                        <h3>@Html.DisplayFor(modelItem => item.Name) - @Html.DisplayFor(modelItem => item.Role)</h3>
                        <p class="p-justify">@Html.DisplayFor(modelItem => item.Description)
                        </p>
                    </div>
                </div>
            </div>
        }
    </div>
    <div class="col-xs-12 col-md-6" id="liziWeddingParty">
        @foreach (var item in Model.Where(modelItem => modelItem.WeddingParty == WeddingParty.Lizi))
        {
            <div class="row">
                <div class="col-xs-12">
                    <div class="col-xs-4">
                        <img class="img-circle"
                             src="@Html.DisplayFor(modelItem => item.ImageSrc)"
                             alt="@Html.DisplayFor(modelItem => item.Name)" />
                    </div>
                    <div class="col-xs-8">
                        <h3>@Html.DisplayFor(modelItem => item.Name) - @Html.DisplayFor(modelItem => item.Role)</h3>
                        <p class="p-justify">
                            @Html.DisplayFor(modelItem => item.Description)
                        </p>
                    </div>
                </div>
            </div>
        }
    </div>

</div>

<script src="https://my.hellobar.com/5fd124e1bfea203694e0c8aebf51717bd32e1641.js" type="text/javascript" charset="utf-8" async="async"></script>

WeddingAzure/Views/Rsvp/Index.cshtml
@using WeddingAzure.Models
@model WeddingAzure.Models.RsvpFormData
@{
    ViewBag.Title = "#Lando2018 - RSVP";
}

<div class="row">
    <div class="col-xs-12"><h2>RSVP</h2></div>
</div>
<hr />
<div class="row">
    <span class="glyphicon glyphicon-heart"></span>
</div>
<hr />
<div class="row">
    <div class="col-xs-1 col-md-2"></div>
    <div class="col-xs-10 col-md-8">
        @using (Html.BeginForm("Index", "Rsvp", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
    {
        <div class="form-group">
            @Html.LabelFor(m => m.NameTextBoxData, new { @class = "col-md-4 control-label" })
            <div class="col-md-8">
                @Html.TextBoxFor(m => m.NameTextBoxData, new { @class = "form-control", placeholder = "Your name(s)" })
                @Html.ValidationMessageFor(m => m.NameTextBoxData, null, new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.AttendingWeddingCheckBox, new { @class = "col-md-4 control-label" })
            <div class="col-md-8">
                @Html.CheckBoxFor(m => m.AttendingWeddingCheckBox, new { @class = "form-control" })
            </div>
            @Html.LabelFor(m => m.WillToastFromAfar, new { @class = "col-md-4 control-label" })
            <div class="col-md-8">
                @Html.CheckBoxFor(m => m.WillToastFromAfar, new { @class = "form-control" })
            </div>
            @Html.LabelFor(m => m.AttendingSundayCheckBox, new { @class = "col-md-4 control-label" })
            <div class="col-md-8">
                @Html.CheckBoxFor(m => m.AttendingSundayCheckBox, new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.DietaryRequirementsTextBoxData, new { @class = "col-md-4 control-label" })
            <div class="col-md-8">
                @Html.TextBoxFor(m => m.DietaryRequirementsTextBoxData, new { @class = "form-control", placeholder = "e.g. Vegan, No Peanuts..." })
                @Html.ValidationMessageFor(m => m.DietaryRequirementsTextBoxData, null, new { @class = "text-danger" })
            </div>
            @Html.LabelFor(m => m.SongRequestTextBoxData, new { @class = "col-md-4 control-label" })
            <div class="col-md-8">
                @Html.TextBoxFor(m => m.SongRequestTextBoxData, new { @class = "form-control", placeholder = "Title, Artist" })
                @Html.ValidationMessageFor(m => m.SongRequestTextBoxData, null, new { @class = "text-danger" })
            </div>
        </div>
        <input type="submit" value="Submit" />
        }
        </div>
        <div class="col-xs-1 col-md-2"></div>
    </div>
<hr />
<div class="row">
    <span class="glyphicon glyphicon-heart"></span>
</div>

WeddingAzure/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <link href="https://fonts.googleapis.com/css?family=Great+Vibes" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Amatic+SC" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Dosis" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Satisfy" rel="stylesheet">

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">

        <div class="navbar-header">
            <div class="navbar-brand">
                <a href="/"><span class="clickable"></span></a>
                <img src="https://landowedding.blob.core.windows.net/public-img/wedding-icon.png" width="250" height="50" alt="">
            </div>
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>
                    <a href="@Url.Action("Index", "Home")">
                        Our Wedding
                        <span class="glyphicon glyphicon-heart" aria-hidden="true"></span>
                    </a>
                </li>
                <li>
                    <a href="@Url.Action("Details", "Home")">
                        Details
                        <span class="glyphicon glyphicon-heart" aria-hidden="true"></span>
                    </a>
                </li>
                <li>
                    <a href="@Url.Action("Gifts", "Home")">
                        Gifts
                        <span class="glyphicon glyphicon-heart" aria-hidden="true"></span>
                    </a>
                </li>
                <li>
                    <a href="@Url.Action("Index", "Gallery")">
                        Gallery
                        <span class="glyphicon glyphicon-heart" aria-hidden="true"></span>
                    </a>
                </li>
            </ul>
        </div>
        <div class="navbar-right" width="250"></div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>Use our hashtag! #Lando2018</p>
            <p>&copy; 2018 - Made with love by Andy Sprague <span class="glyphicon glyphicon-heart"></span></p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>